
pace.MiscIcons = {
	about = "icon16/star.png",
	appearance = "icon16/paintcan.png",
	autoload = "icon16/transmit_go.png",
	chat = "icon16/comment.png",
	clear = "icon16/cross.png",
	clone = "icon16/page_copy.png",
	copy = "icon16/page_white_text.png",
	edit = "icon16/table_edit.png",
	error = "icon16/exclamation.png",
	exit = "icon16/cancel.png",
	font = "icon16/text_smallcaps.png",
	help = "icon16/help.png",
	info = "icon16/information.png",
	language = "icon16/user_comment.png",
	load = "icon16/folder.png",
	new = "icon16/add.png",
	orientation = "icon16/shape_handles.png",
	outfit = "icon16/group.png",
	paste = "icon16/paste_plain.png",
	replace = "icon16/arrow_refresh.png",
	revert = "icon16/table_delete.png",
	save = "icon16/disk.png",
	uniqueid = "icon16/vcard.png",
	url = "icon16/server_go.png",
	warning = "icon16/error.png",
	wear = "icon16/transmit.png",
}

pace.GroupsIcons = {
	effects = 'icon16/wand.png',
	model = 'icon16/shape_square.png',
	entity = 'icon16/brick.png',
	modifiers = 'icon16/disconnect.png',
	advanced = 'icon16/page_white_gear.png',
	experimental = 'icon16/bug.png',
	legacy = 'icon16/hourglass.png',
}
