pace.Materials = {}

pace.Materials.trails =
{
	"trails/plasma",
	"trails/tube",
	"trails/electric",
	"trails/smoke",
	"trails/laser",
	"trails/physbeam",
	"trails/love",
	"trails/lol"
}

pace.Materials.sprites = 
{
	"sprites/glow04_noz",
	"sprites/grip",
	"sprites/key_0",
	"sprites/key_1",
	"sprites/key_10",
	"sprites/key_11",
	"sprites/key_12",
	"sprites/key_13",
	"sprites/key_14",
	"sprites/key_15",
	"sprites/key_2",
	"sprites/key_3",
	"sprites/key_4",
	"sprites/key_5",
	"sprites/key_6",
	"sprites/key_7",
	"sprites/key_8",
	"sprites/key_9",
	"sprites/light_ignorez",
	"sprites/muzzleflash4",
	"sprites/orangecore1",
	"sprites/orangecore2",
	"sprites/orangeflare1",
	"sprites/orangelight1",
	"sprites/orangelight1_noz",
	"sprites/physbeam",
	"sprites/physbeama",
	"sprites/physg_glow1",
	"sprites/physg_glow2",
	"sprites/physgbeamb",
	"sprites/redglow1",
	"sprites/640_logo",
	"sprites/640_pain",
	"sprites/640_train",
	"sprites/640hud1",
	"sprites/640hud2",
	"sprites/640hud3",
	"sprites/640hud4",
	"sprites/640hud5",
	"sprites/640hud6",
	"sprites/640hud7",
	"sprites/640hud8",
	"sprites/640hud9",
	"sprites/a_icons1",
	"sprites/animglow01",
	"sprites/animglow02",
	"sprites/ar2_muzzle1",
	"sprites/ar2_muzzle1b",
	"sprites/ar2_muzzle2b",
	"sprites/ar2_muzzle3",
	"sprites/ar2_muzzle3b",
	"sprites/ar2_muzzle4",
	"sprites/ar2_muzzle4b",
	"sprites/arrow",
	"sprites/autoaim_1a",
	"sprites/autoaim_1b",
	"sprites/bigspit",
	"sprites/blackbeam",
	"sprites/blood",
	"sprites/bloodspray",
	"sprites/blueflare1",
	"sprites/blueflare1_noz",
	"sprites/blueglow1",
	"sprites/blueglow2",
	"sprites/bluelaser1",
	"sprites/bluelight1",
	"sprites/blueshaft1",
	"sprites/bubble",
	"sprites/combineball_glow_black_1",
	"sprites/combineball_glow_blue_1",
	"sprites/combineball_glow_red_1",
	"sprites/combineball_trail_black_1",
	"sprites/combineball_trail_blue_1",
	"sprites/combineball_trail_red_1",
	"sprites/crosshair_h",
	"sprites/crosshair_v",
	"sprites/crosshairs",
	"sprites/crosshairs_tluc",
	"sprites/crystal_beam1",
	"sprites/d_icons",
	"sprites/dot",
	"sprites/fire",
	"sprites/fire1",
	"sprites/fire2",
	"sprites/fire_floor",
	"sprites/fire_floor_subrect",
	"sprites/fireburst",
	"sprites/flame01",
	"sprites/flame03",
	"sprites/flame04",
	"sprites/flamefromabove",
	"sprites/flamelet1",
	"sprites/flamelet2",
	"sprites/flamelet3",
	"sprites/flamelet4",
	"sprites/flamelet5",
	"sprites/flare1",
	"sprites/flatflame",
	"sprites/floorfire4_",
	"sprites/FloorFlame",
	"sprites/floorflame2",
	"sprites/FlyingEmber",
	"sprites/glow01",
	"sprites/glow02",
	"sprites/glow03",
	"sprites/glow04",
	"sprites/glow05",
	"sprites/glow06",
	"sprites/glow07",
	"sprites/glow08",
	"sprites/glow1",
	"sprites/glow1_noz",
	"sprites/glow_test01",
	"sprites/glow_test01b",
	"sprites/glow_test02",
	"sprites/greenglow1",
	"sprites/greenspit1",
	"sprites/gunsmoke",
	"sprites/halo01",
	"sprites/heatwave",
	"sprites/heatwavedx70",
	"sprites/hud1",
	"sprites/hydragutbeam",
	"sprites/hydragutbeamcap",
	"sprites/hydraspinalcord",
	"sprites/lamphalo",
	"sprites/lamphalo1",
	"sprites/laser",
	"sprites/laserbeam",
	"sprites/laserdot",
	"sprites/lgtning",
	"sprites/lgtning_noz",
	"sprites/light_glow01",
	"sprites/light_glow02",
	"sprites/light_glow02_add",
	"sprites/light_glow02_add_noz",
	"sprites/light_glow02_noz",
	"sprites/light_glow03",
	"sprites/muzzleflash1",
	"sprites/muzzleflash2",
	"sprites/muzzleflash3",
	"sprites/obsolete",
	"sprites/old_Aexplo",
	"sprites/old_Cexplo",
	"sprites/old_richo2",
	"sprites/old_XFire",
	"sprites/orangeglow1",
	"sprites/physcannon_bluecore1",
	"sprites/physcannon_bluecore1b",
	"sprites/physcannon_bluecore2",
	"sprites/physcannon_bluecore2b",
	"sprites/physcannon_blueflare1",
	"sprites/physcannon_blueglow",
	"sprites/physcannon_bluelight1",
	"sprites/physcannon_bluelight1b",
	"sprites/physcannon_bluelight2",
	"sprites/physring1",
	"sprites/plasma",
	"sprites/plasma1",
	"sprites/plasmabeam",
	"sprites/plasmaember",
	"sprites/plasmahalo",
	"sprites/predator",
	"sprites/purpleglow1",
	"sprites/purplelaser1",
	"sprites/qi_center",
	"sprites/redglow2",
	"sprites/redglow3",
	"sprites/redglow4",
	"sprites/reticle",
	"sprites/reticle1",
	"sprites/reticle2",
	"sprites/richo1",
	"sprites/rico1",
	"sprites/rico1_noz",
	"sprites/rollermine_shock",
	"sprites/scanner",
	"sprites/scanner_bottom",
	"sprites/scanner_dots1",
	"sprites/scanner_dots2",
	"sprites/shellchrome",
	"sprites/smoke",
	"sprites/splodesprite",
	"sprites/spotlight",
	"sprites/sprite_fire01",
	"sprites/steam1",
	"sprites/strider_blackball",
	"sprites/strider_bluebeam",
	"sprites/tp_beam001",
	"sprites/vortring1",
	"sprites/w_icons1",
	"sprites/w_icons1b",
	"sprites/w_icons2",
	"sprites/w_icons2b",
	"sprites/w_icons3",
	"sprites/w_icons3b",
	"sprites/white",
	"sprites/WXplo1",
	"sprites/XBeam2",
	"sprites/yellowflare",
	"sprites/yellowglow1",
	"sprites/zerogxplode",
	"sprites/grubflare1",
	"sprites/bucket_bat_blue",
	"sprites/bucket_bat_red",
	"sprites/bucket_bonesaw",
	"sprites/bucket_bottle_blue",
	"sprites/bucket_bottle_red",
	"sprites/bucket_fireaxe",
	"sprites/bucket_fists_blue",
	"sprites/bucket_fists_red",
	"sprites/bucket_flamethrower_blue",
	"sprites/bucket_flamethrower_red",
	"sprites/bucket_grenlaunch",
	"sprites/bucket_knife",
	"sprites/bucket_machete",
	"sprites/bucket_medigun_blue",
	"sprites/bucket_medigun_red",
	"sprites/bucket_minigun",
	"sprites/bucket_nailgun",
	"sprites/bucket_pda",
	"sprites/bucket_pda_build",
	"sprites/bucket_pda_destroy",
	"sprites/bucket_pipelaunch",
	"sprites/bucket_pistol",
	"sprites/bucket_revolver",
	"sprites/bucket_rl",
	"sprites/bucket_sapper",
	"sprites/bucket_scatgun",
	"sprites/bucket_shotgun",
	"sprites/bucket_shovel",
	"sprites/bucket_smg",
	"sprites/bucket_sniper",
	"sprites/bucket_syrgun_blue",
	"sprites/bucket_syrgun_red",
	"sprites/bucket_tranq",
	"sprites/bucket_wrench",
	"sprites/healbeam",
	"sprites/healbeam_blue",
	"sprites/healbeam_red",
	"sprites/640_pain_down",
	"sprites/640_pain_left",
	"sprites/640_pain_right",
	"sprites/640_pain_up",
	"sprites/bomb_carried",
	"sprites/bomb_carried_ring",
	"sprites/bomb_carried_ring_offscreen",
	"sprites/bomb_dropped",
	"sprites/bomb_dropped_ring",
	"sprites/bomb_planted",
	"sprites/bomb_planted_ring",
	"sprites/c4",
	"sprites/cbbl_smoke",
	"sprites/defuser",
	"sprites/glow",
	"sprites/halo",
	"sprites/hostage_following",
	"sprites/hostage_following_offscreen",
	"sprites/hostage_rescue",
	"sprites/ledglow",
	"sprites/numbers",
	"sprites/objective_rescue",
	"sprites/objective_site_a",
	"sprites/objective_site_b",
	"sprites/player_blue_dead",
	"sprites/player_blue_dead_offscreen",
	"sprites/player_blue_offscreen",
	"sprites/player_blue_self",
	"sprites/player_blue_small",
	"sprites/player_hostage_dead",
	"sprites/player_hostage_dead_offscreen",
	"sprites/player_hostage_offscreen",
	"sprites/player_hostage_small",
	"sprites/player_radio_ring",
	"sprites/player_radio_ring_offscreen",
	"sprites/player_red_dead",
	"sprites/player_red_dead_offscreen",
	"sprites/player_red_offscreen",
	"sprites/player_red_self",
	"sprites/player_red_small",
	"sprites/player_tick",
	"sprites/radar",
	"sprites/radar_trans",
	"sprites/radio",
	"sprites/scope_arc",
	"sprites/shopping_cart",
	"sprites/spectator_3rdcam",
	"sprites/spectator_eye",
	"sprites/spectator_freecam",
	"sprites/water_drop",
	"sprites/wpn_select1",
	"sprites/wpn_select2",
	"sprites/wpn_select3",
	"sprites/wpn_select4",
	"sprites/wpn_select5",
	"sprites/wpn_select6",
	"sprites/wpn_select7",
	"sprites/xfireball3",
	"sprites/yelflare1",
	"sprites/yelflare2",
	"sprites/frostbreath",
	"sprites/cloudglow1_nofog",
	"sprites/core_beam1",
	"sprites/rollermine_shock_yellow",
	"sprites/yellowlaser1",
	"sprites/bluelight",
	"sprites/grav_beam",
	"sprites/grav_beam_noz",
	"sprites/grav_flare",
	"sprites/grav_light",
	"sprites/orangelight",
	"sprites/portalgun_effects",
	"sprites/redlaserglow",
	"sprites/sphere_silhouette",
	"sprites/track_beam",
	"sprites/redglow_mp1",
	"sprites/sent_ball",
	"sprites/magic",
	"sprites/soul",
	"particle/bendibeam",
	"particle/bendibeam_cheap",
	"particle/blood_core",
	"particle/fire",
	"particle/particle_cloud",
	"particle/particle_composite",
	"particle/Particle_Crescent",
	"particle/Particle_Crescent_Additive",
	"particle/Particle_Debris_01",
	"particle/Particle_Debris_02",
	"particle/Particle_Glow_01",
	"particle/Particle_Glow_01_Add_NoFog",
	"particle/Particle_Glow_01_Additive",
	"particle/Particle_Glow_02",
	"particle/Particle_Glow_02_Additive",
	"particle/Particle_Glow_03",
	"particle/Particle_Glow_03_Additive",
	"particle/Particle_Glow_04",
	"particle/Particle_Glow_04_Additive",
	"particle/Particle_Glow_05",
	"particle/Particle_Glow_05_Add_15OB_MinSize",
	"particle/Particle_Glow_05_Add_15OB_MinSizeBig",
	"particle/Particle_Glow_05_Add_15OB_NoZ",
	"particle/Particle_Glow_05_Additive",
	"particle/Particle_Glow_05_AddNoFog",
	"particle/Particle_Glow_06",
	"particle/Particle_Glow_07",
	"particle/Particle_Glow_07_15OB",
	"particle/Particle_Glow_08",
	"particle/Particle_Glow_09",
	"particle/particle_glow_10",
	"particle/particle_glow_11",
	"particle/particle_noisesphere",
	"particle/Particle_Ring_Blur",
	"particle/Particle_Ring_Blur_Add_15_OverBright",
	"particle/Particle_Ring_Blur_Additive",
	"particle/particle_ring_refract_01",
	"particle/Particle_Ring_Sharp",
	"particle/Particle_Ring_Sharp_Additive",
	"particle/Particle_Ring_Wave",
	"particle/Particle_Ring_Wave_10",
	"particle/Particle_Ring_Wave_2",
	"particle/Particle_Ring_Wave_2_Add",
	"particle/Particle_Ring_Wave_2_Add_15OB",
	"particle/Particle_Ring_Wave_3",
	"particle/Particle_Ring_Wave_3_Add",
	"particle/Particle_Ring_Wave_3_Add_15OB",
	"particle/Particle_Ring_Wave_4",
	"particle/Particle_Ring_Wave_4_Add",
	"particle/Particle_Ring_Wave_4_Add_15OB",
	"particle/Particle_Ring_Wave_4_NoFog",
	"particle/Particle_Ring_Wave_5",
	"particle/Particle_Ring_Wave_5_Add",
	"particle/Particle_Ring_Wave_5_Add_15OB",
	"particle/Particle_Ring_Wave_6",
	"particle/Particle_Ring_Wave_6_Add",
	"particle/Particle_Ring_Wave_6_Add_15OB",
	"particle/Particle_Ring_Wave_7",
	"particle/Particle_Ring_Wave_7_Add",
	"particle/Particle_Ring_Wave_7_Add_15OB",
	"particle/Particle_Ring_Wave_8",
	"particle/Particle_Ring_Wave_8_15OB_NoFog",
	"particle/Particle_Ring_Wave_9",
	"particle/Particle_Ring_Wave_Additive",
	"particle/Particle_Ring_Wave_AddNoFog",
	"particle/particle_smokegrenade",
	"particle/particle_smokegrenade1",
	"particle/particle_sphere",
	"particle/Particle_Sphere_Additive_15OB",
	"particle/Particle_Sphere_Additive_NoZ_15OB",
	"particle/Particle_Square_Gradient",
	"particle/Particle_Square_Gradient_NoFog",
	"particle/Particle_Swirl_03",
	"particle/Particle_Swirl_04",
	"particle/rain",
	"particle/screenspace_fog",
	"particle/smokesprites_0001",
	"particle/smokesprites_0002",
	"particle/smokesprites_0003",
	"particle/smokesprites_0004",
	"particle/smokesprites_0005",
	"particle/smokesprites_0006",
	"particle/smokesprites_0007",
	"particle/smokesprites_0008",
	"particle/smokesprites_0009",
	"particle/smokesprites_0010",
	"particle/smokesprites_0011",
	"particle/smokesprites_0012",
	"particle/smokesprites_0013",
	"particle/smokesprites_0014",
	"particle/smokesprites_0015",
	"particle/smokesprites_0016",
	"particle/SmokeStack",
	"particle/snow",
	"particle/sparkles",
	"particle/warp1_dx8",
	"particle/warp1_warp",
	"particle/warp2_warp",
	"particle/warp3_warp_NoZ",
	"particle/warp4_dx8",
	"particle/warp4_warp",
	"particle/warp4_warp_NoZ",
	"particle/warp5_warp",
	"particle/warp_ripple",
	"particle/animglow02",
	"particle/beam_smoke_01",
	"particle/beam_smoke_02",
	"particle/bendibeam_nofog",
	"particle/glow_haze_nofog",
	"particle/particle_cloud2",
	"particle/particle_electrical_arc",
	"particle/particle_vortring1",
	"particle/smoke_black_smokestack000",
	"particle/smoke_black_smokestack001",
	"particle/smoke_black_smokestack_all",
	"particle/smokestack_nofog",
	"particle/particle_rockettrail1",
	"particle/particle_rockettrail2",
	"particle/Particle_Sphere_Additive_15OB_nodepth",
	"particle/Particle_Swirl_04_nodepth",
	"particle/Particle_Glow_05_Add_15OB",
	"particles/balloon_bit",
	"particles/fire1",
	"particles/fire_glow",
	"particles/flamelet1",
	"particles/flamelet2",
	"particles/flamelet3",
	"particles/flamelet4",
	"particles/flamelet5",
	"particles/smokey",
	"particles/Smoke01_L",
}

local PANEL = {}

PANEL.ClassName = "mat_browser_sheet"
PANEL.Base = "DPanel"

AccessorFunc(PANEL, "m_Selected", "Selected")

function PANEL:Init()
	local list = vgui.Create("DPanelList", self)
		list:SetPadding(2)
		list:SetSpacing(2)
		list:EnableVerticalScrollbar(true)
		list:EnableHorizontal(true)
		list:Dock(FILL)		
	self.MatList = list
end

function PANEL:SetMaterialList(tbl)
	self:SetSelected()
	
	self.MaterialList = tbl
	
	self.MatList:Clear(true)
	
	for i, material in ipairs(self.MaterialList) do
		local image = vgui.Create("DImageButton")
		image:SetOnViewMaterial(material, material)
		image:SetSize(64, 64)
		image.Value = material
		
		self.MatList:AddItem(image)
		
		image.DoClick = function(image) self:SetSelected(image.Value) end
		
		if self:GetSelected() then
			image.PaintOver = HighlightedButtonPaint
			self:SetSelected(material)
		end
	end
	
	self:InvalidateLayout(true)
end

pace.RegisterPanel(PANEL)

local PANEL = {}

PANEL.Base = "DFrame"
PANEL.ClassName = "mat_browser"

function PANEL:Init()
	self:SetTitle("materials")

	local list = 
	{
		{key = "default", val = list.Get("OverrideMaterials")},
		{key = "sprites", val = pace.Materials.sprites},
		{key = "trails", val = pace.Materials.trails},
	}

	local sheet = vgui.Create("DPropertySheet", self)
	sheet:Dock(FILL)
	
	for _, data in ipairs(list) do
		local name, tbl = data.key, data.val
		local pnl = pace.CreatePanel("mat_browser_sheet", self)
		pnl:SetMaterialList(tbl)
		pnl.SetSelected = function(_, path) self:SetSelected(path) end
		sheet:AddSheet(name, pnl)
	end

	local entry = vgui.Create("DTextEntry", self)
		entry.OnEnter = function() self:SetSelected(self.Entry:GetValue()) end
		entry:Dock(BOTTOM)
		entry:SetTall(20)
	self.Entry = entry
	
	self:SetDrawOnTop(true)
	self:SetSize(300, 300)
	self:SetSizable(true)
	self:Center()
end

function PANEL:SetSelected(value)
	self.Entry:SetText(value or "")

	self.m_Selected = value
	
	self:MaterialSelected(value)
end

function PANEL:MaterialSelected(path) end

pace.RegisterPanel(PANEL)