return {
unlitgeneric = {
	detailtexturetransform = {
		friendly = "DetailTextureTransform",
		type = "matrix",
		default = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
		description = "$detail texcoord transform",
		gmod_default = "[ 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 ]",
	},
	outlineend0 = {
		friendly = "OutlineEnd0",
		type = "float",
		default = "0.0",
		description = "inner end value for outline",
		gmod_default = "0.000000",
	},
	distancealphafromdetail = {
		friendly = "DistanceAlphaFromDetail",
		type = "bool",
		default = "0",
		description = "Take the distance-coded alpha mask from the detail texture.",
		gmod_default = "0",
	},
	gammacolorread = {
		friendly = "GammaColorRead",
		type = "integer",
		default = "0",
		description = "Disables SRGB conversion of color texture read.",
		gmod_default = "0",
	},
	envmapmask = {
		type = "texture",
		friendly = "EnvmapMask",
		description = "envmap mask",
		--default = "shadertest/shadertest_envmask",
	},
	phongwarptexture = {
		type = "texture",
		friendly = "PhongWarpTexture",
		description = "2D map for warping specular",
		default = "shadertest/BaseTexture",
	},
	envmapcameraspace = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "EnvmapCameraSpace",
	},
	detailframe = {
		friendly = "DetailFrame",
		type = "integer",
		default = "0",
		description = "frame number for $detail",
		gmod_default = "0",
	},
	outlinestart1 = {
		friendly = "OutlineStart1",
		type = "float",
		default = "0.0",
		description = "inner start value for outline",
		gmod_default = "0.000000",
	},
	BaseTextureTransform = {
		type = "matrix",
		friendly = "BaseTextureTransform",
		default = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
		description = "Base Texture Texcoord Transform",
	},
	phongboost = {
		friendly = "PhongBoost",
		type = "float",
		default = "1.0",
		description = "Phong overbrightening factor (specular mask channel should be authored to account for this)",
		gmod_default = "0.000000",
	},
	phongtint = {
		friendly = "PhongTint",
		type = "vec3",
		default = "5.0",
		description = "Phong tint for local specular lights",
		gmod_default = "[ 0.000000 0.000000 0.000000 ]",
	},
	glowcolor = {
		friendly = "GlowColor",
		type = "color",
		default = "[1 1 1]",
		description = "color of outter glow for distance coded line art.",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	envmapcontrast = {
		friendly = "EnvmapContrast",
		type = "float",
		default = "0.0",
		description = "contrast 0 == normal 1 == color*color",
		gmod_default = "0.000000",
	},
	SrgbTint = {
		type = "color",
		friendly = "SrgbTint",
		default = "[1 1 1]",
		description = "tint value to be applied when running on new-style srgb parts",
	},
	glowy = {
		friendly = "GlowY",
		type = "float",
		default = "0",
		description = "texture offset y for glow mask.",
		gmod_default = "0.000000",
	},
	noalphamod = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NoAlphaMod",
	},
	znearer = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Znearer",
	},
	envmap = {
		type = "texture",
		friendly = "Envmap",
		description = "envmap",
		--default = "shadertest/shadertest_env",
	},
	linearwrite = {
		friendly = "LinearWrite",
		type = "integer",
		default = "0",
		description = "Disables SRGB conversion of shader results.",
		gmod_default = "0",
	},
	--[[Flags_defined2 = {
		type = "integer",
		friendly = "_FlagsDefined2",
		default = "0",
		description = "flags2_defined",
	},]]
	glowx = {
		friendly = "GlowX",
		type = "float",
		default = "0",
		description = "texture offset x for glow mask.",
		gmod_default = "0.000000",
	},
	distancealpha = {
		friendly = "DistanceAlpha",
		type = "bool",
		default = "0",
		description = "Use distance-coded alpha generated from hi-res texture by vtex.",
		gmod_default = "0",
	},
	glowend = {
		friendly = "GlowEnd",
		type = "float",
		default = "0.5",
		description = "end value for glow/shadow",
		gmod_default = "0.000000",
	},
	edgesoftnessstart = {
		friendly = "EdgeSoftnessStart",
		type = "float",
		default = "0.6",
		description = "Start value for soft edges for distancealpha.",
		gmod_default = "0.500000",
	},
	detailblendfactor = {
		friendly = "DetailTextureBlendFactor",
		type = "float",
		default = "1",
		description = "blend amount for detail texture.",
		gmod_default = "1.000000",
	},
	use_in_fillrate_mode = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "UseInFillrateMode",
	},
	envmapsphere = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "EnvmapSphere",
	},
	albedo = {
		type = "texture",
		friendly = "PhongAlbedo",
		description = "albedo (Base texture with no baked lighting)",
		default = "shadertest/BaseTexture",
	},
	glowalpha = {
		friendly = "GlowAlpha",
		type = "float",
		default = "1",
		description = "Base glow alpha amount for glows/shadows with distance alpha.",
		gmod_default = "1.000000",
	},
	texture = {
		type = "texture",
		description = "base texture",
	},
	selfillummask = {
		type = "texture",
		friendly = "SelfIllumMask",
		description = "If we bind a texture here, it overrides base alpha (if any) for self illum",
		default = "shadertest/BaseTexture",
	},
	basetexture = {
		type = "texture",
		description = "base texture",
		default = "models/effects/comball_glow1"
	},
	scaleedgesoftnessbasedonscreenres = {
		friendly = "ScaleEdgeSoftnessBasedOnScreenRes",
		type = "bool",
		default = "0",
		description = "Scale the size of the soft edges based upon resolution. 1024x768 = nominal.",
		gmod_default = "0",
	},
	basetexture2 = {
		type = "texture",
		description = "base texture",
	},
	texture2 = {
		type = "texture",
		description = "base texture",
	},
	debug = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Debug",
	},
	wireframe = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Wireframe",
	},
	envmapmasktransform = {
		friendly = "EnvmapMaskTransform",
		type = "matrix",
		default = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
		description = "$envmapmask texcoord transform",
		gmod_default = "[ 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 ]",
	},
	flat = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Flat",
	},
	detail = {
		type = "texture",
		friendly = "Detail",
		description = "detail texture",
		default = "shadertest/detail",
	},
	envmapmode = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "EnvmapMode",
	},
	vertexalpha = {
		is_flag = true,
		type = "bool",
		default = "0",
		description = "flag",
		friendly = "VertexAlpha",
	},
	nofog = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Nofog",
	},
	FlashLightTexture = {
		type = "texture",
		friendly = "FlashLightTexture",
		default = "effects/flashlight001",
		description = "flashlight spotlight shape texture",
	},
	outlinestart0 = {
		friendly = "OutlineStart0",
		type = "float",
		default = "0.0",
		description = "outer start value for outline",
		gmod_default = "0.000000",
	},
	suppress_decals = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "SuppressDecals",
	},
	Frame = {
		type = "integer",
		friendly = "Frame",
		default = "0",
		description = "Animation Frame",
	},
	BaseTexture = {
		type = "texture",
		friendly = "BaseTexture",
		default = "shadertest/BaseTexture",
		description = "Base Texture with lighting built in",
	},
	nolod = {
		type = "bool",
		default = "0",
		description = "flag",
		friendly = "nolod",
	},
	opaquetexture = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "OpaqueTexture",
	},
	ignorez = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Ignorez",
	},
	detailblendmode = {
		friendly = "DetailTextureCombineMode",
		type = "integer",
		default = "0",
		description = "mode for combining detail texture with base. 0=normal, 1= additive, 2=alpha blend detail over base, 3=crossfade",
		gmod_default = "0",
	},
	normalmapalphaenvmapmask = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NormalmapAlphaEnvmapMask",
	},
	Color2 = {
		type = "color",
		friendly = "Color2",
		default = "[1 1 1]",
		description = "color2",
	},
	outlineend1 = {
		friendly = "OutlineEnd1",
		type = "float",
		default = "0.0",
		description = "outer end value for outline",
		gmod_default = "0.000000",
	},
	basealphaenvmapmask = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "BaseAlphaEnvmapMask",
	},
	glowstart = {
		friendly = "GlowStart",
		type = "float",
		default = "0.7",
		description = "start value for glow/shadow",
		gmod_default = "0.000000",
	},
	decal = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Decal",
	},
	--[[Flags_defined = {
		type = "integer",
		friendly = "_FlagsDefined",
		default = "0",
		description = "flags_defined",
	},]]
	needs_software_skinning = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NeedsSoftwareSkinning",
	},
	detailscale = {
		friendly = "DetailScale",
		type = "float",
		default = "4",
		description = "scale of the detail texture",
		gmod_default = "4.000000",
	},
	envmapmaskframe = {
		friendly = "EnvmapMaskFrame",
		type = "integer",
		default = "0",
		description = "",
		gmod_default = "0",
	},
	nocull = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NoCull",
	},
	model = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Model",
	},
	lightwarptexture = {
		type = "texture",
		friendly = "DiffuseWarpTexture",
		description = "1D ramp texture for tinting scalar diffuse term",
		default = "shadertest/BaseTexture",
	},
	additive = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Additive",
	},
	alphatest = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "AlphaTest",
	},
	envmaptint = {
		friendly = "EnvmapTint",
		type = "color",
		default = "[1 1 1]",
		description = "envmap tint",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	FlashLightTextureframe = {
		type = "integer",
		friendly = "FlashLightTextureframe",
		default = "0",
		description = "Animation Frame for $flashlight",
	},
	hdrcolorscale = {
		friendly = "HDRColorScale",
		type = "float",
		default = "1.0",
		description = "hdr color scale",
		gmod_default = "1.000000",
	},
	softedges = {
		friendly = "SoftEdges",
		type = "bool",
		default = "0",
		description = "Enable soft edges to distance coded textures.",
		gmod_default = "0",
	},
	selfillum = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "SelfIllum",
	},
	ignore_alpha_modulation = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "IgnoreAlphaModulation",
	},
	envmapsaturation = {
		friendly = "EnvmapSaturation",
		type = "float",
		default = "1.0",
		description = "saturation 0 == greyscale 1 == normal",
		gmod_default = "1.000000",
	},
	vertexcolor = {
		is_flag = true,
		type = "bool",
		default = "0",
		description = "flag",
		friendly = "VertexColor",
	},
	no_draw = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NoDraw",
	},
	phongexponent = {
		friendly = "PhongExponent",
		type = "float",
		default = "5.0",
		description = "Phong exponent for local specular lights",
		gmod_default = "0.000000",
	},
	separatedetailuvs = {
		friendly = "SeparateDetailUVs",
		type = "bool",
		default = "0",
		description = "Use texcoord1 for detail texture",
		gmod_default = "0",
	},
	edgesoftnessend = {
		friendly = "EdgeSoftnessEnd",
		type = "float",
		default = "0.5",
		description = "End value for soft edges for distancealpha.",
		gmod_default = "0.500000",
	},
	Alpha = {
		type = "float",
		friendly = "Alpha",
		default = "1.0",
		description = "alpha",
	},
	scaleoutlinesoftnessbasedonscreenres = {
		friendly = "ScaleOutlineSoftnessBasedOnScreenRes",
		type = "bool",
		default = "0",
		description = "Scale the size of the soft part of the outline based upon resolution. 1024x768 = nominal.",
		gmod_default = "0",
	},
	vertexalphatest = {
		friendly = "VertexAlphaTest",
		type = "bool",
		default = "0",
		description = "",
		gmod_default = "0",
	},
	no_debug_override = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NoDebugOverride",
	},
	receiveflashlight = {
		friendly = "ReceiveFlashlight",
		type = "bool",
		default = "0",
		description = "Forces this material to receive flashlights.",
		gmod_default = "0",
	},
	halflambert = {
		is_flag = true,
		type = "bool",
		default = "0",
		description = "flag",
		friendly = "HalfLambert",
	},
	glow = {
		friendly = "Glow",
		type = "bool",
		default = "0",
		description = "Enable glow/shadow for distance coded textures.",
		gmod_default = "0",
	},
	outlinealpha = {
		friendly = "OutlineAlpha",
		type = "float",
		default = "0.0",
		description = "alpha value for outline",
		gmod_default = "1.000000",
	},
	outline = {
		friendly = "Outline",
		type = "bool",
		default = "0",
		description = "Enable outline for distance coded textures.",
		gmod_default = "0",
	},
	--[[Flags = {
		type = "integer",
		friendly = "Flags",
		default = "0",
		description = "flags",
	},
	Flags2 = {
		type = "integer",
		friendly = "Flags2",
		default = "0",
		description = "flags2",
	},]]
	Color = {
		type = "color",
		friendly = "Color",
		default = "[1 1 1]",
		description = "color",
	},
	phongalbedotint = {
		friendly = "PhongAlbedoTint",
		type = "bool",
		default = "1.0",
		description = "Apply tint by albedo (controlled by spec exponent texture",
		gmod_default = "0",
	},
	phongexponenttexture = {
		type = "texture",
		friendly = "PhongExponentTexture",
		description = "Phong Exponent map",
		default = "shadertest/BaseTexture",
	},
	phong = {
		friendly = "Phong",
		type = "bool",
		default = "0",
		description = "enables phong lighting",
		gmod_default = "0",
	},
	alphatestreference = {
		friendly = "AlphaTestReference",
		type = "float",
		default = "0.7",
		description = "",
		gmod_default = "0.000000",
		recompute = true,
	},
	allowalphatocoverage = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "AllowAlphaToCoverage",
	},
	phongfresnelranges = {
		friendly = "PhongFresnelRanges",
		type = "vec3",
		default = "[0  0.5  1]",
		description = "Parameters for remapping fresnel output",
		gmod_default = "[ 0.000000 0.000000 0.000000 ]",
	},
	multipass = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Multipass",
	},
	depthblend = {
		type = "integer",
		gmod_default = "0",
		description = "fade at intersection boundaries",
		default = "0",
	},
	outlinecolor = {
		friendly = "OutlineColor",
		type = "color",
		default = "[1 1 1]",
		description = "color of outline for distance coded images.",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	depthblendscale = {
		type = "float",
		gmod_default = "50.000000",
		description = "Amplify or reduce DEPTHBLEND fading. Lower values make harder edges.",
		default = "50.0",
	},
	translucent = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Translucent",
	},
	envmapframe = {
		friendly = "EnvmapFrame",
		type = "integer",
		default = "",
		description = "envmap frame number",
		gmod_default = "0",
	},
},
vertexlitgeneric = {
	bumpmap = {
		type = "texture",
		friendly = "Bumpmap",
		description = "bump map",
		default = "models/shadertest/shader1_normal",
	},
	bumpstretch = {
		type = "texture",
		friendly = "WrinkleBumpStretch",
		description = "expansion bump map",
		default = "models/shadertest/shader1_normal",
	},
	phongwarptexture = {
		type = "texture",
		friendly = "PhongWarpTexture",
		description = "warp the specular term",
		default = "shadertest/BaseTexture",
	},
	detailframe = {
		friendly = "DetailFrame",
		type = "integer",
		default = "0",
		description = "frame number for $detail",
		gmod_default = "0",
	},
	stretch = {
		type = "texture",
		friendly = "WrinkleStretch",
		description = "expansion wrinklemap",
		default = "shadertest/BaseTexture",
	},
	ignorez = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Ignorez",
	},
	BaseTextureTransform = {
		type = "matrix",
		friendly = "BaseTextureTransform",
		default = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
		description = "Base Texture Texcoord Transform",
	},
	cloakpassenabled = {
		type = "bool",
		gmod_default = "0",
		description = "Enables cloak render in a second pass",
		default = "0",
		friendly = "CloakPassEnabled",
	},
	seamless_scale = {
		friendly = "SeamlessScale",
		type = "float",
		default = "1.0",
		description = "the scale for the seamless mapping. # of repetions of texture per inch.",
		gmod_default = "0.000000",
	},
	rimlight = {
		friendly = "RimLight",
		type = "bool",
		default = "0",
		description = "enables rim lighting",
		gmod_default = "0",
	},
	selfillum_envmapmask_alpha = {
		friendly = "SelfIllumEnvMapMask_Alpha",
		type = "float",
		default = "0.0",
		description = "defines that self illum value comes from env map mask alpha",
		gmod_default = "0.000000",
	},
	flesheffectcenterradius4 = {
		friendly = "FleshEffectCenterRadius4",
		type = "vec4",
		default = "[0 0 0 0.001]",
		description = "Flesh effect center and radius",
		gmod_default = "[ 0.000000 0.000000 0.000000 0.000000 ]",
	},
	envmapcontrast = {
		friendly = "EnvmapContrast",
		type = "float",
		default = "0.0",
		description = "contrast 0 == normal 1 == color*color",
		gmod_default = "0.000000",
	},
	fleshscrollspeed = {
		friendly = "FleshScrollSpeed",
		type = "float",
		default = "1.0",
		description = "Flesh scroll speed",
		gmod_default = "0.000000",
	},
	znearer = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Znearer",
	},
	fleshborderwidth = {
		friendly = "FleshBorderWidth",
		type = "float",
		default = "0.3",
		description = "Flesh border",
		gmod_default = "0.000000",
	},
	detailtint = {
		friendly = "DetailTint",
		type = "color",
		default = "[1 1 1]",
		description = "detail texture tint",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	--[[Flags_defined2 = {
		type = "integer",
		friendly = "_FlagsDefined2",
		default = "0",
		description = "flags2_defined",
	},]]
	detailblendfactor = {
		friendly = "DetailTextureBlendFactor",
		type = "float",
		default = "1",
		description = "blend amount for detail texture.",
		gmod_default = "1.000000",
	},
	envmapsphere = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "EnvmapSphere",
	},
	sheenmapmaskframe = {
		type = "integer",
		description = "",
		default = "0",
		friendly = "SheenmapMaskFrame",
	},
	selfillum = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "SelfIllum",
	},
	selfillummask = {
		type = "texture",
		friendly = "SelfIllumMask",
		description = "If we bind a texture here, it overrides base alpha (if any) for self illum",
		default = "shadertest/BaseTexture",
	},
	rimlightexponent = {
		friendly = "RimLightPower",
		type = "float",
		default = "4.0",
		description = "Exponent for rim lights",
		gmod_default = "0.000000",
	},
	seamless_detail = {
		friendly = "SeamlessDetail",
		type = "bool",
		default = "0",
		description = "where to apply seamless mapping to the detail texture.",
		gmod_default = "0",
	},
	flat = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Flat",
	},
	sheenmapmaskscalex = {
		type = "float",
		description = "X Scale the size of the map mask to the size of the target",
		default = "1",
		friendly = "SheenmapMaskScaleX",
	},
	sheenindex = {
		type = "integer",
		description = "Index of the Effect Type (Color Additive, Override etc...)",
		default = "0",
		friendly = "SheenmapIndex",
	},
	BaseTexture = {
		type = "texture",
		friendly = "BaseTexture",
		default = "shadertest/BaseTexture",
		description = "Base Texture with lighting built in",
	},
	nolod = {
		type = "bool",
		default = "0",
		description = "flag",
		friendly = "nolod",
	},
	fleshbordersoftness = {
		friendly = "FleshBorderSoftness",
		type = "float",
		default = "0.42",
		description = "Flesh border softness (> 0.0 && <= 0.5)",
		gmod_default = "0.000000",
	},
	sheenmapmaskoffsetx = {
		type = "float",
		description = "X Offset of the mask relative to model space coords of target",
		default = "0",
		friendly = "SheenmapMaskOffsetX",
	},
	emissiveblendflowtexture = {
		type = "texture",
		friendly = "EmissiveBlendFlowTexture",
		description = "flow map",
		default = "",
	},
	model = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Model",
	},
	additive = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Additive",
	},
	blendtintcoloroverbase = {
		type = "float",
		gmod_default = "0.000000",
		description = "blend between tint acting as a multiplication versus a replace",
		default = "0",
	},
	Color = {
		type = "color",
		friendly = "Color",
		default = "[1 1 1]",
		description = "color",
	},
	FlashLightTextureframe = {
		type = "integer",
		friendly = "FlashLightTextureframe",
		default = "0",
		description = "Animation Frame for $flashlight",
	},
	phongfresnelranges = {
		friendly = "PhongFresnelRanges",
		type = "vec3",
		default = "[0  0.5  1]",
		description = "Parameters for remapping fresnel output",
		gmod_default = "[ 0.000000 0.000000 0.000000 ]",
	},
	envmapfresnel = {
		friendly = "EnvmapFresnel",
		type = "float",
		default = "0",
		description = "Degree to which Fresnel should be applied to env map",
		gmod_default = "0.000000",
	},
	fleshcubetexture = {
		type = "texture",
		friendly = "FleshCubeTexture",
		description = "Flesh cubemap texture",
		default = "",
	},
	envmapsaturation = {
		friendly = "EnvmapSaturation",
		type = "float",
		default = "1.0",
		description = "saturation 0 == greyscale 1 == normal",
		gmod_default = "1.000000",
	},
	refractamount = {
		type = "float",
		gmod_default = "0.000000",
		description = "",
		default = "2",
		friendly = "CloakRefractAmount",
	},
	phongexponent = {
		friendly = "PhongExponent",
		type = "float",
		default = "5.0",
		description = "Phong exponent for local specular lights",
		gmod_default = "0.000000",
	},
	separatedetailuvs = {
		friendly = "SeparateDetailUVs",
		type = "bool",
		default = "0",
		description = "Use texcoord1 for detail texture",
		gmod_default = "0",
	},
	alphatest = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "AlphaTest",
	},
	sheenmapmaskoffsety = {
		type = "float",
		description = "Y Offset of the mask relative to model space coords of target",
		default = "0",
		friendly = "SheenmapMaskOffsetY",
	},
	halflambert = {
		is_flag = true,
		type = "bool",
		default = "0",
		description = "flag",
		friendly = "HalfLambert",
	},
	ambientonly = {
		friendly = "AmbientOnly",
		type = "bool",
		default = "0",
		description = "Control drawing of non-ambient light ()",
		gmod_default = "0",
	},
	fleshinteriornoisetexture = {
		type = "texture",
		friendly = "FleshNoiseTexture",
		description = "Flesh noise texture",
		default = "",
	},
	phongexponenttexture = {
		type = "texture",
		friendly = "PhongExponentTexture",
		description = "Phong Exponent map",
		default = "shadertest/BaseTexture",
	},
	phong = {
		friendly = "Phong",
		type = "bool",
		default = "0",
		description = "enables phong lighting",
		gmod_default = "0",
	},
	alphatestreference = {
		friendly = "AlphaTestReference",
		type = "float",
		default = "0.0",
		description = "",
		gmod_default = "0.000000",
		recompute = true,
	},
	allowalphatocoverage = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "AllowAlphaToCoverage",
	},
	multipass = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Multipass",
	},
	depthblendscale = {
		type = "float",
		gmod_default = "50.000000",
		description = "Amplify or reduce DEPTHBLEND fading. Lower values make harder edges.",
		default = "50.0",
	},
	detailtexturetransform = {
		friendly = "DetailTextureTransform",
		type = "matrix",
		default = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
		description = "$detail texcoord transform",
		gmod_default = "[ 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 ]",
	},
	emissiveblendtint = {
		friendly = "EmissiveBlendTint",
		type = "color",
		default = "[1 1 1]",
		description = "Self-illumination tint",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	envmapmask = {
		type = "texture",
		friendly = "EnvmapMask",
		description = "envmap mask",
		default = "shadertest/shadertest_envmask",
	},
	envmapcameraspace = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "EnvmapCameraSpace",
	},
	basemapalphaphongmask = {
		friendly = "BaseMapAlphaPhongMask",
		type = "integer",
		default = "0",
		description = "indicates that there is no normal map and that the phong mask is in base alpha",
		gmod_default = "0",
	},
	fleshglossbrightness = {
		friendly = "FleshGlossBrightness",
		type = "float",
		default = "0.66",
		description = "Flesh gloss brightness",
		gmod_default = "0.000000",
	},
	no_debug_override = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NoDebugOverride",
	},
	--[[time = {
		friendly = "Time",
		type = "float",
		default = "0.0",
		description = "Needs CurrentTime Proxy",
		gmod_default = "0.000000",
	},]]
	fleshbordertexture1d = {
		type = "texture",
		friendly = "FleshBorderTexture1D",
		description = "Flesh border 1D texture",
		default = "",
	},
	phongtint = {
		friendly = "PhongTint",
		type = "vec3",
		default = "5.0",
		description = "Phong tint for local specular lights",
		gmod_default = "[ 0.000000 0.000000 0.000000 ]",
	},
	--[[Flags = {
		type = "integer",
		friendly = "Flags",
		default = "0",
		description = "flags",
	},]]
	sheenmap = {
		type = "texture",
		description = "sheenmap",
		default = "shadertest/shadertest_env",
		friendly = "Sheenmap",
	},
	SrgbTint = {
		type = "color",
		friendly = "SrgbTint",
		default = "[1 1 1]",
		description = "tint value to be applied when running on new-style srgb parts",
	},
	fleshsubsurfacetexture = {
		type = "texture",
		friendly = "FleshSubsurfaceTexture",
		description = "Flesh subsurface texture",
		default = "",
	},
	noalphamod = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NoAlphaMod",
	},
	envmap = {
		type = "texture",
		friendly = "Envmap",
		description = "envmap",
		default = "shadertest/shadertest_env",
	},
	sheenmapmaskscaley = {
		type = "float",
		description = "Y Scale the size of the map mask to the size of the target",
		default = "1",
		friendly = "SheenmapMaskScaleY",
	},
	nocull = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NoCull",
	},
	selfillumtint = {
		friendly = "SelfIllumTint",
		type = "color",
		default = "[1 1 1]",
		description = "Self-illumination tint",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	sheenmaptint = {
		type = "color",
		description = "sheenmap tint",
		default = "[1 1 1]",
		friendly = "SheenmapTint",
	},
	no_draw = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NoDraw",
	},
	sheenpassenabled = {
		type = "bool",
		description = "Enables weapon sheen render in a second pass",
		default = "0",
		firendly = "SheenmapPassEnabled",
	},
	cloakcolortint = {
		type = "color",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
		description = "Cloak color tint",
		default = "[1 1 1]",
		friendly = "CloakColorTint",
	},
	use_in_fillrate_mode = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "UseInFillrateMode",
	},
	albedo = {
		type = "texture",
		friendly = "PhongAlbedo",
		description = "albedo (Base texture with no baked lighting)",
		default = "shadertest/BaseTexture",
	},
	phongalbedotint = {
		friendly = "PhongAlbedoTint",
		type = "bool",
		default = "1.0",
		description = "Apply tint by albedo (controlled by spec exponent texture",
		gmod_default = "0",
	},
	fleshinteriortexture = {
		type = "texture",
		friendly = "FleshTexture",
		description = "Flesh color texture",
		default = "",
	},
	debug = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Debug",
	},
	wireframe = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Wireframe",
	},
	rimmask = {
		friendly = "RimMask",
		type = "bool",
		default = "0",
		description = "Indicates whether or not to use alpha channel of exponent texture to mask the rim term",
		gmod_default = "0",
	},
	fleshnormaltexture = {
		type = "texture",
		friendly = "FleshNormalTexture",
		description = "Flesh normal texture",
		default = "",
	},
	detail = {
		type = "texture",
		friendly = "Detail",
		description = "detail texture",
		default = "shadertest/detail",
	},
	nofog = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Nofog",
	},
	--[[texture = {
		type = "texture",
		description = "base texture",
	},]]
	basetexture = {
		type = "texture",
		description = "base texture",
	},
	flesheffectcenterradius3 = {
		friendly = "FleshEffectCenterRadius3",
		type = "vec4",
		default = "[0 0 0 0.001]",
		description = "Flesh effect center and radius",
		gmod_default = "[ 0.000000 0.000000 0.000000 0.000000 ]",
	},
	compress = {
		type = "texture",
		friendly = "WrinkleCompress",
		description = "compression wrinklemap",
		default = "shadertest/BaseTexture",
	},
	basetexture2 = {
		type = "texture",
		description = "base texture",
	},
	--[[texture2 = {
		type = "texture",
		description = "base texture",
	},]]
	ignore_alpha_modulation = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "IgnoreAlphaModulation",
	},
	fleshsubsurfacetint = {
		friendly = "FleshSubsurfaceTint",
		type = "color",
		default = "[1 1 1]",
		description = "Subsurface Color",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	envmapmasktransform = {
		friendly = "EnvmapMaskTransform",
		type = "matrix",
		default = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
		description = "$envmapmask texcoord transform",
		gmod_default = "[ 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 ]",
	},
	Color2 = {
		type = "color",
		friendly = "Color2",
		default = "[1 1 1]",
		description = "color2",
	},
	envmapmode = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "EnvmapMode",
	},
	opaquetexture = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "OpaqueTexture",
	},
	needs_software_skinning = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NeedsSoftwareSkinning",
	},
	normalmapalphaenvmapmask = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "NormalmapAlphaEnvmapMask",
	},
	--[[Flags_defined = {
		type = "integer",
		friendly = "_FlagsDefined",
		default = "0",
		description = "flags_defined",
	},]]
	bumpframe = {
		friendly = "BumpFrame",
		type = "integer",
		default = "0",
		description = "frame number for $bumpmap",
		gmod_default = "0",
	},
	--[[Flags2 = {
		type = "integer",
		friendly = "Flags2",
		default = "0",
		description = "flags2",
	},]]
	fleshbordernoisescale = {
		friendly = "FleshBorderNoiseScale",
		type = "float",
		default = "1.5",
		description = "Flesh Noise UV scalar for border",
		gmod_default = "0.000000",
	},
	basealphaenvmapmask = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "BaseAlphaEnvmapMask",
	},
	decal = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Decal",
	},
	fleshglobalopacity = {
		friendly = "FleshGlobalOpacity",
		type = "float",
		default = "1.0",
		description = "Flesh global opacity",
		gmod_default = "0.000000",
	},
	fleshdebugforcefleshon = {
		friendly = "FleshDebugForceFleshOn",
		type = "bool",
		default = "0",
		description = "Flesh Debug full flesh",
		gmod_default = "0",
	},
	invertphongmask = {
		friendly = "InvertPhongMask",
		type = "bool",
		default = "0",
		description = "invert the phong mask (0=full phong, 1=no phong)",
		gmod_default = "0",
	},
	envmaptint = {
		friendly = "EnvmapTint",
		type = "color",
		default = "[1 1 1]",
		description = "envmap tint",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	detailblendmode = {
		friendly = "DetailTextureCombineMode",
		type = "integer",
		default = "0",
		description = "mode for combining detail texture with base. 0=normal, 1= additive, 2=alpha blend detail over base, 3=crossfade",
		gmod_default = "0",
		enums = {normal = 0, additive = 1, alphablend = 2, crossfade = 3},
	},
	flashlightnolambert = {
		friendly = "FlashlightNoLambert",
		type = "bool",
		default = "0",
		description = "Flashlight pass sets N.L=1.0",
		gmod_default = "0",
	},
	lightwarptexture = {
		type = "texture",
		friendly = "DiffuseWarpTexture",
		description = "1D ramp texture for tinting scalar diffuse term",
		default = "shadertest/BaseTexture",
	},
	emissiveblendtexture = {
		type = "texture",
		friendly = "EmissiveBlendTexture",
		description = "self-illumination map",
		default = "",
	},
	flesheffectcenterradius2 = {
		friendly = "FleshEffectCenterRadius2",
		type = "vec4",
		default = "[0 0 0 0.001]",
		description = "Flesh effect center and radius",
		gmod_default = "[ 0.000000 0.000000 0.000000 0.000000 ]",
	},
	cloakfactor = {
		type = "float",
		gmod_default = "0.000000",
		description = "",
		default = "0.0",
		friendly = "CloakFactor",
	},
	FlashLightTexture = {
		type = "texture",
		friendly = "FlashLightTexture",
		default = "effects/flashlight001",
		description = "flashlight spotlight shape texture",
	},
	emissiveblendstrength = {
		friendly = "EmissiveBlendStrength",
		type = "float",
		default = "1.0",
		description = "Emissive blend strength",
		gmod_default = "0.000000",
	},
	bumptransform = {
		friendly = "BumpTransform",
		type = "matrix",
		default = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
		description = "$bumpmap texcoord transform",
		gmod_default = "[ 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 1.000 ]",
	},
	emissiveblendscrollvector = {
		friendly = "EmissiveBlendScrollVector",
		type = "vec2",
		default = "[0.11 0.124]",
		description = "Emissive scroll vec",
		gmod_default = "[ 0.000000 0.000000 ]",
	},
	suppress_decals = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "SuppressDecals",
	},
	Alpha = {
		type = "float",
		friendly = "Alpha",
		default = "1.0",
		description = "alpha",
	},
	sheenmapmask = {
		type = "texture",
		description = "sheenmap mask",
		default = "shadertest/shadertest_envmask",
		friendly = "SheenmapMask",
	},
	selfillumfresnel = {
		friendly = "SelfIllumFresnel",
		type = "bool",
		default = "0",
		description = "Self illum fresnel",
		gmod_default = "0",
	},
	blendtintbybasealpha = {
		friendly = "BlendTintByBaseAlpha",
		type = "bool",
		default = "0",
		description = "Use the base alpha to blend in the $color modulation",
		gmod_default = "0",
	},
	selfillumfresnelminmaxexp = {
		friendly = "SelfIllumFresnelMinMaxExp",
		type = "vec4",
		default = "0",
		description = "Self illum fresnel min, max, exp",
		gmod_default = "[ 0.000000 0.000000 0.000000 0.000000 ]",
	},
	bumpcompress = {
		type = "texture",
		friendly = "WrinkleBumpCompress",
		description = "compression bump map",
		default = "models/shadertest/shader3_normal",
	},
	emissiveblendbasetexture = {
		type = "texture",
		friendly = "EmissiveBlendBaseTexture",
		description = "self-illumination map",
		default = "",
	},
	sheenmapmaskdirection = {
		type = "integer",
		description = "The direction the sheen should move (length direction of weapon) XYZ, 0,1,2",
		default = "0",
		friendly = "SheenmapDirection",
	},
	rimlightboost = {
		friendly = "RimLightBoost",
		type = "float",
		default = "1.0",
		description = "Boost for rim lights",
		gmod_default = "0.000000",
	},
	envmapmaskframe = {
		friendly = "EnvmapMaskFrame",
		type = "integer",
		default = "0",
		description = "",
		gmod_default = "0",
	},
	detailscale = {
		friendly = "DetailScale",
		type = "float",
		default = "4",
		description = "scale of the detail texture",
		gmod_default = "4.000000",
	},
	emissiveblendenabled = {
		type = "bool",
		gmod_default = "0",
		description = "Enable emissive blend pass",
		default = "0",
		friendly = "EmissiveBlendEnabled",
	},
	Frame = {
		type = "integer",
		friendly = "Frame",
		default = "0",
		description = "Animation Frame",
	},
	fleshinteriorenabled = {
		type = "bool",
		gmod_default = "0",
		description = "Enable Flesh interior blend pass",
		default = "0",
		friendly = "FleshInteriorEnabled",
	},
	flesheffectcenterradius1 = {
		friendly = "FleshEffectCenterRadius1",
		type = "vec4",
		default = "[0 0 0 0.001]",
		description = "Flesh effect center and radius",
		gmod_default = "[ 0.000000 0.000000 0.000000 0.000000 ]",
	},
	vertexalpha = {
		is_flag = true,
		type = "bool",
		default = "0",
		description = "flag",
		friendly = "VertexAlpha",
	},
	seamless_base = {
		friendly = "SeamlessBase",
		type = "bool",
		default = "0",
		description = "whether to apply seamless mapping to the base texture. requires a smooth model.",
		gmod_default = "0",
	},
	fleshbordertint = {
		friendly = "FleshBorderTint",
		type = "color",
		default = "[1 1 1]",
		description = "Flesh border Color",
		gmod_default = "[ 1.000000 1.000000 1.000000 ]",
	},
	phongboost = {
		friendly = "PhongBoost",
		type = "float",
		default = "1.0",
		description = "Phong overbrightening factor (specular mask channel should be authored to account for this)",
		gmod_default = "0.000000",
	},
	depthblend = {
		type = "bool",
		gmod_default = "0",
		description = "fade at intersection boundaries. Only supported without bumpmaps",
		default = "0",
	},
	linearwrite = {
		friendly = "LinearWrite",
		type = "bool",
		default = "0",
		description = "Disables SRGB conversion of shader results.",
		gmod_default = "0",
	},
	vertexcolor = {
		is_flag = true,
		type = "bool",
		default = "0",
		description = "flag",
		friendly = "VertexColor",
	},
	translucent = {
		is_flag = true,
		type = "integer",
		default = "0",
		description = "flag",
		friendly = "Translucent",
	},
	envmapframe = {
		friendly = "EnvmapFrame",
		type = "integer",
		default = "0",
		description = "envmap frame number",
		gmod_default = "0",
	},
},


}